### ISSUE TITLE
Findbugs issues: OS_OPEN_STREAM

### ISSUE THREAD

**Issue by SonOfFlyingPig** [FINRAOS/JTAF-ExtWebDriver#106]
Running Findbugs on EWD revealed the following instance of issue OBL_UNSATISFIED_OBLIGATION: OS_OPEN_STREAM

[INFO] org.finra.jtaf.ewd.impl.DefaultSessionFactory.addPreferences(FirefoxProfile, String) may fail to close stream [org.finra.jtaf.ewd.impl.DefaultSessionFactory] At DefaultSessionFactory.java:[line 516] OS_OPEN_STREAM

**Comment by dpulitano** [comment]
This came up from selenium-firefox-driver 2.53.0's FirefoxProfile class.

There is a block, which is unlikely to, but 'can' inadvertedly throw an exception if a certain user.js file isn't in a readable directory (FirefoxProfile.class line 68). If it throws it, an InputStream reader will not be closed. We can maybe suggest they put the method in question's reader.close() block into a method that would be instead called in a finally clause

**Comment by mibrahim** [comment]
Just a recommendation, you can also use try with resource and let java handle the closing when appropriate. That will reduce the complexity of your code.

**Comment by dpulitano** [comment]
It looks that the generated line number above isn't correct anymore.. and the error doesn't traverse down to selenium..

I can submit a change that using try with resources in our DefaultSessionFactory class for the FileInputStream in private static void addPreferences(FirefoxProfile ffp, String propertiesFile), to ensure it is being closed...

This will require the source and target versions in the maven-compiler-plugin to be updated to 1.7 from 1.6.
@SonOfFlyingPig @mibrahim What are thoughts on doing this? This can help reduce complexity of code in a lot of cases

**Comment by SonOfFlyingPig** [comment]
Yes, I think it's good to switch to 1.7

**Comment by dpulitano** [comment]
@SonOfFlyingPig can you review and merge when you're able to?
Thank you.

**Comment by SonOfFlyingPig** [comment]
Closed by #141
