### ISSUE TITLE
InteractiveElement.type() Fails When Text is Single Quote Character

### ISSUE THREAD

**Issue by mikeastarb** [FINRAOS/JTAF-ExtWebDriver#94]
InteractiveElement:301 - If javascript type mode is on and the text is a single quote character, the javascript that gets executed becomes "arguments[0].value=''';" which fails to evaluate.

In my project, we have some test cases that need to type a single quote into a text box.  For reasons outside of the scope of this issue, my test enters this using the JS type mode.

Instead of putting it on the users to constantly remember to escape their single quotes, I believe it would be easier and cleaner for EWD to escape the characters automatically (if they haven't been escaped by the user) before evaluating the Javascript.

Thoughts?

**Comment by kood1** [comment]
@mikeastarb Sounds like a good idea.  Why don't you go ahead and make a PR?

**Comment by mikeastarb** [comment]
@kood1 Sure thing, I'll see if I can get it done this afternoon

**Comment by SonOfFlyingPig** [comment]
@mikeastarb We can close this now, yes?

**Comment by mikeastarb** [comment]
Ah, yes. I didn't realize it hadn't auto-closed
